import { useEffect, useState } from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount } from "wagmi";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { fetchNFTs } from "../utils/fetchNFTs";

const Home = () => {
  const { address, isConnected } = useAccount();
  const [nft, setNft] = useState<{ image: string; name: string; description: string } | null>(null);

  useEffect(() => {
    if (isConnected && address) {
      fetchNFTs(address).then(setNft);
    }
  }, [address, isConnected]);

  return (
    <div className={styles.container}>
      <Head>
        <title>RanaMarketplace</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <h1 className={styles.title}>
          Welcome to <a href="https://puppyscan.shib.io/token/0xDB929853F31f9cfccF753A2Cec27c6A37c9D8bFa">Rana Art Collection</a> Marketplace
        </h1>
        <p className={styles.description}>Buy Rana Art Collection</p>

        {nft ? (
          <div className={styles.nftContainer}>
            <h2>{nft.name}</h2>
            <img src={nft.image} alt={nft.name} className={styles.nftImage} />
            <p>{nft.description}</p>
          </div>
        ) : (
          <p>No NFTs found</p>
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://mayankrana.in" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by Mayank Rana
        </a>
      </footer>
    </div>
  );
};

export default Home;
