import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RanaMarketplace</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="https://puppyscan.shib.io/token/0xDB929853F31f9cfccF753A2Cec27c6A37c9D8bFa">Rana Art Collection</a> Marketplace          
        </h1>

        <p className={styles.description}>
          Buy Rana Art Collection          
        </p>

       
      </main>

      <footer className={styles.footer}>
        <a href="https://mayankrana.in" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by Mayank Rana
        </a>
      </footer>
    </div>
  );
};

export default Home;
